### ISSUE TITLE
ERROR: Lita::Handlers::Standup crashed

### ISSUE THREAD

**Issue by 1010dvpt** [chriswoodrich/lita-standup#3]
Hi Chris,  I have Lita up and running with redis in docker containers.  Other lita addons I have are working great.  When I ask Lita to 'start standup now'  I get the following output.  I'm still new to ruby and hope there is an easy solution.  Much appreciated.  logs below:

`Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using bundler 1.11.2
Using concurrent-ruby 1.0.1
Using eventmachine 1.0.9.1
Using multipart-post 2.0.0
Using websocket-extensions 0.1.2
Using rack 1.6.4
Using i18n 0.7.0
Using ice_nine 0.11.2
Using multi_json 1.11.2
Using puma 3.1.0
Using rb-readline 0.5.3
Using redis 3.2.2
Using thor 0.19.1
Using mime-types 2.99.1
Using sucker_punch 2.0.1
Using faraday 0.9.2
Using websocket-driver 0.6.3
Using url_mount 0.2.1
Using redis-namespace 1.5.2
Using mail 2.6.3
Using faye-websocket 0.10.3
Using http_router 0.11.2
Using lita 4.7.0
Using lita-retro 1.0.0
Using lita-slack 1.7.2
Using lita-standup 0.0.2
Bundle complete! 5 Gemfile dependencies, 26 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into /var/bundle.
[2016-03-08 20:39:58 UTC] INFO: Connected to Slack.

[2016-03-08 20:43:33 UTC] ERROR: Lita::Handlers::Standup crashed. The exception was:
undefined method `each' for nil:NilClass
Full backtrace:
/var/bundle/ruby/2.3.0/gems/lita-standup-0.0.2/lib/lita/handlers/standup.rb:42:in`message_all_users'
/var/bundle/ruby/2.3.0/gems/lita-standup-0.0.2/lib/lita/handlers/standup.rb:26:in `begin_standup'
/var/bundle/ruby/2.3.0/gems/lita-4.7.0/lib/lita/callback.rb:31:in`public_send'
/var/bundle/ruby/2.3.0/gems/lita-4.7.0/lib/lita/callback.rb:31:in `call'
/var/bundle/ruby/2.3.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:97:in`dispatch_to_route'
/var/bundle/ruby/2.3.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:82:in `block in dispatch'
/var/bundle/ruby/2.3.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:72:in`map'
/var/bundle/ruby/2.3.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:72:in `dispatch'
/var/bundle/ruby/2.3.0/gems/lita-4.7.0/lib/lita/robot.rb:69:in`block in receive'
/usr/local/lib/ruby/2.3.0/set.rb:306:in `each_key'
/usr/local/lib/ruby/2.3.0/set.rb:306:in`each'
/var/bundle/ruby/2.3.0/gems/lita-4.7.0/lib/lita/robot.rb:66:in `map'
/var/bundle/ruby/2.3.0/gems/lita-4.7.0/lib/lita/robot.rb:66:in`receive'
/var/bundle/ruby/2.3.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/message_handler.rb:119:in `dispatch_message'
/var/bundle/ruby/2.3.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/message_handler.rb:159:in`handle_message'
/var/bundle/ruby/2.3.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/message_handler.rb:18:in `handle'
/var/bundle/ruby/2.3.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/rtm_connection.rb:100:in`block in receive_message'
/var/bundle/ruby/2.3.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/event_loop.rb:10:in `block in defer'
/var/bundle/ruby/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in`block in spawn_threadpool'
`

my lita_config.rb file

`Lita.configure do |config|
  # The name your robot will use.
  config.robot.name = "Lita"

  # The locale code for the language to use.
  # config.robot.locale = :en

  # The severity of messages to log. Options are:
  # :debug, :info, :warn, :error, :fatal
  # Messages at the selected level and above will be logged.
  config.robot.log_level = :info

  # An array of user IDs that are considered administrators. These users
  # the ability to add and remove other users from authorization groups.
  # What is considered a user ID will change depending on which adapter you use.
  config.robot.admins = ["xxxx", "xxxx"]

  # The adapter you want to connect with. Make sure you've added the
  # appropriate gem to the Gemfile.
  config.robot.adapter = :slack
  config.adapters.slack.token = "xxxx"

  ## Example: Set options for the chosen adapter.
  # config.adapter.username = "myname"
  # config.adapter.password = "secret"

  ## Example: Set options for the Redis connection.
   config.redis[:host] = ENV["REDIS_PORT_6379_TCP_ADDR"]
   config.redis[:port] = ENV["REDIS_PORT_6379_TCP_PORT"]

  ## Example: Set configuration for any loaded handlers. See the handler's
  ## documentation for options.
  # config.handlers.some_handler.some_config_key = "value"

  ### Stand-up Settings

  # General settings
  config.handlers.standup.time_to_respond = 60  # type: Integer, default: 60 (minutes)
  config.handlers.standup.summary_email_recipients =  ['fulladdress@email.com', 'fulladdress@email.com'] # type: Array, required: true
  config.handlers.standup.name_of_auth_group = :standup_participants   # type: Symbol, required: true

  ## SMTP Mailer settings
  config.handlers.standup.address = 'smtp.office365.com' # type: String, required: true
  config.handlers.standup.port = 587              # type: Integer, required: true
  config.handlers.standup.domain = 'DOMAIN' # type: String, required: true
  config.handlers.standup.user_name = 'fulladdress@email.com'     # type: String, required: true
  config.handlers.standup.password = 'xxxxxx'     # type: String, required: true
  config.handlers.standup.authentication = 'plain'          # type: String, required: true
  config.handlers.standup.enable_starttls_auto = true             # type: true || false, required: true

end`

**Comment by chriswoodrich** [comment]
I will look into this tonight.  I suspect it's an issue where the auth group `:standup_participants` is empty and causing `#message_all_users` to fail.

**Comment by 1010dvpt** [comment]
Awesome.  You were right, I set myself as a standup_admins, thought I had added my self to the standup_paticipants (nope that was the last docker build :-/).  Was not in there, did that now.  I did get the DM from lita though and was able to respond with success.  Closer, but I do still see this error in the log.

`[2016-03-08 22:20:18 UTC] ERROR: Lita::Handlers::Standup crashed. The exception was:
undefined method`async' for #SummaryEmailJob:0x007f4bb8269480
Full backtrace:
/var/bundle/ruby/2.3.0/bundler/gems/lita-standup-0ca1ea2234e3/lib/lita/handlers/standup.rb:27:in `begin_standup'
/var/bundle/ruby/2.3.0/gems/lita-4.7.0/lib/lita/callback.rb:31:in`public_send'
/var/bundle/ruby/2.3.0/gems/lita-4.7.0/lib/lita/callback.rb:31:in `call'
/var/bundle/ruby/2.3.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:97:in`dispatch_to_route'
/var/bundle/ruby/2.3.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:82:in `block in dispatch'
/var/bundle/ruby/2.3.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:72:in`map'
/var/bundle/ruby/2.3.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:72:in `dispatch'
/var/bundle/ruby/2.3.0/gems/lita-4.7.0/lib/lita/robot.rb:69:in`block in receive'
/usr/local/lib/ruby/2.3.0/set.rb:306:in `each_key'
/usr/local/lib/ruby/2.3.0/set.rb:306:in`each'
/var/bundle/ruby/2.3.0/gems/lita-4.7.0/lib/lita/robot.rb:66:in `map'
/var/bundle/ruby/2.3.0/gems/lita-4.7.0/lib/lita/robot.rb:66:in`receive'
/var/bundle/ruby/2.3.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/message_handler.rb:119:in `dispatch_message'
/var/bundle/ruby/2.3.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/message_handler.rb:159:in`handle_message'
/var/bundle/ruby/2.3.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/message_handler.rb:18:in `handle'
/var/bundle/ruby/2.3.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/rtm_connection.rb:100:in`block in receive_message'
/var/bundle/ruby/2.3.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/event_loop.rb:10:in `block in defer'
/var/bundle/ruby/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in`block in spawn_threadpool'`

**Comment by chriswoodrich** [comment]
Alright I'll see about that tonight.
