### ISSUE TITLE
ERROR: Lita::Handlers::Standup crashed (different issue)

### ISSUE THREAD

**Issue by ghost** [chriswoodrich/lita-standup#4]
Hey Chris,

I looked at the previous issue and confirmed that there were participants in both standup_admins and standup_participants groups, but I am still getting the same error but the stack trace is different 

`[2016-07-11 07:15:56 UTC] ERROR: Lita::Handlers::Standup crashed. The exception was:
undefined method 'private_message?' for #Lita::User:0x007f889c951600
Did you mean?  private_methods

Full backtrace:
/usr/local/lib/ruby/gems/2.3.0/gems/lita-irc-2.0.3/lib/lita/adapters/irc.rb:49:in 'send_messages'
/usr/local/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/robot.rb:129:in 'send_messages'
/usr/local/lib/ruby/gems/2.3.0/gems/lita-standup-0.0.2/lib/lita/handlers/standup.rb:43:in 'block in message_all_users'
/usr/local/lib/ruby/gems/2.3.0/gems/lita-standup-0.0.2/lib/lita/handlers/standup.rb:42:in 'each'
/usr/local/lib/ruby/gems/2.3.0/gems/lita-standup-0.0.2/lib/lita/handlers/standup.rb:42:in 'message_all_users'
/usr/local/lib/ruby/gems/2.3.0/gems/lita-standup-0.0.2/lib/lita/handlers/standup.rb:26:in 'begin_standup'
/usr/local/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/callback.rb:31:in 'public_send'
/usr/local/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/callback.rb:31:in 'call'
/usr/local/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:97:in 'dispatch_to_route'
/usr/local/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:82:in 'block in dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:72:in 'map'
/usr/local/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:72:in 'dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/robot.rb:69:in 'block in receive'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/set.rb:306:in 'each_key'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/set.rb:306:in 'each'
/usr/local/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/robot.rb:66:in 'map'
/usr/local/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/robot.rb:66:in 'receive'
/usr/local/lib/ruby/gems/2.3.0/gems/lita-irc-2.0.3/lib/lita/adapters/irc/cinch_plugin.rb:38:in 'dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/lita-irc-2.0.3/lib/lita/adapters/irc/cinch_plugin.rb:18:in 'execute'
/usr/local/lib/ruby/gems/2.3.0/gems/cinch-2.3.2/lib/cinch/plugin.rb:418:in 'call'
/usr/local/lib/ruby/gems/2.3.0/gems/cinch-2.3.2/lib/cinch/plugin.rb:418:in 'block (2 levels) in __register_matchers'
/usr/local/lib/ruby/gems/2.3.0/gems/cinch-2.3.2/lib/cinch/handler.rb:99:in 'block in call'
`

**Comment by patrickgates** [comment]
Fixed in recent Pull Request. If it doesn't get accepted soon you're more than welcome to add my version into your gemfile using;

gem "lita-standup", :git => 'https://github.com/patrickgates/lita-standup.git'

**Comment by chriswoodrich** [comment]
Fixed in https://github.com/chriswoodrich/lita-standup/pull/5
